### ISSUE TITLE
Type 'typeof CalendarComponent' has no properties in common with type '{ read?: any; }'

### ISSUE THREAD

**Issue by picosam** [Centeva/ngx-datepicker#14]
Hello, I'm trying your component, but am unable to compile it. I'm getting the following:
`ERROR in /Users/Sammy/Projects/example/node_modules/ct-ngx-datepicker/src/dualpicker/dualpicker.component.ts (110,24): Type 'typeof CalendarComponent' has no properties in common with type '{ read?: any; }'.`

**Comment by marbletravis** [comment]
Hello, just to confirm, this is happening on line 110 of dualpicker.component.ts, which for me is

`@ViewChild('cal2', CalendarComponent) public cal2: CalendarComponent;`

Correct?

Second, since I have a terrible readme for developing. Can you confirm that you are using one of the following commands:

`grunt build`
`grunt watch`

Other webpack commands do work (grunt is just pointing to different config files).

**Comment by marbletravis** [comment]
Also, if you don't need to modify the source, you can use the umd under the dist folder.

**Comment by anhany** [comment]
@picosam Are you using the most current version of the datepicker / TypeScript / Angular?

**Comment by picosam** [comment]
Hello, yes I am.

**Comment by picosam** [comment]
I'm not using `grunt` at all, simply `angular-cli`

**Comment by marbletravis** [comment]
Try version 3.0.3 we addressed some issues with the index.js not pointing to the UMD.

**Comment by anhany** [comment]
@picosam A new version was just published (3.1.1) that updates the ViewChild syntax around that line of code. Give that a go and let me know how it works out for you.
